apiVersion: v1
kind: Service
metadata:
  name: mi-servicio
spec:
  type: NodePort       # <--- Esto expone el puerto hacia afuera
  selector:
    app: testcontaineropenshift        # Debe coincidir con el label de tu Pod
  ports:
    - port: 8080        # El puerto del Servicio
      targetPort: 8080   # El puerto de tu contenedor (Dockerfile)
      nodePort: 30007  # (Opcional) El puerto externo fijo (30000-32767)